name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install the necessary packages
        run: pip3.10 install -r requirements.txt

      - name: Run unit tests for flight service
        run: pytest -vs reservation_service/tests/reservation.py

  deploy:
    name: Deploy service on VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Copy code to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "reservation_service,payment_service,loyalty_service,gateway_service,docker,docker-compose.yml,requirements.txt"
          target: /home/${{ secrets.SSH_USERNAME }}/hotel-booking-system

      - name: Run app on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/hotel-booking-system
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose down
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi gateway_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi reservation_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi payment_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi loyalty_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi gateway_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d

  # autograding:
  #   name: Autograding
  #   needs: [deploy]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
    
  #     - name: Run API Tests
  #       uses: matt-ball/newman-action@master
  #       with:
  #         collection: v2/postman/collection.json
  #         environment: v2/postman/environment.json
  #         delayRequest: 100
  #         reporters: '[ "cli" ]'
          